REGISTER pigGene.jar;
R1 = LOAD '$input.txt' USING pigGene.PigGeneStorage();
R2 = FILTER R1 BY chrom == 12;
R3 = LOAD '$reference.vcf' USING pigGene.PigGeneStorage();
R4 = JOIN R2 BY (chrom,pos), R3 BY (chrom,pos);
STORE R4 INTO '$output';
REGISTER asdf;
REGISTER asdf;
REGISTER asdf;
REGISTER asdg;
REGISTER asdf;
REGISTER asdf;
REGISTER asdf;
asdf = LOAD '$asdf' USING pigGene.PigGeneStorage();
REGISTER asdf;
REGISTER asdfas;
REGISTER qwer;
REGISTER erz;
REGISTER er;
REGISTER werz;
REGISTER qerqerz;
REGISTER wwetwe;
REGISTER werwert;
REGISTER wertwert;
REGISTER werwet;
REGISTER wertwert;
